### ISSUE TITLE
allow conditional resolution of the kms alias

### ISSUE THREAD

**Issue by mishabruml** [mpirik/serverless-kms-alias#3]
hey, i'm having trouble deploying my stack using this framework, where I need to conditonally deploy an IAM role statement that allows lambda to decrypt a KMS key, the arn of which is resolved by alias with the plugin

when deploying to localstack for offline development, we don't use the KMS key and so don't deploy it, and therefore the plugin fails when trying to resolve the KMS arn

I've tried many different ways of wrapping the plugin and conitional parent resource in conditional/environment-dependent statements with no luck, because it seems like resolving the KMS key ARN happens early on in the serverless lifecycle; even `sls print` will fail, unfortunately

**Comment by jgeurts** [comment]
Hi @mishabruml

Please give v2.1.0 a try. I added the ability to [specify stages to enable the plugin](https://github.com/mpirik/serverless-kms-alias#example---enable-for-specific-stages).

You can specify custom configuration like:

```
custom:
  kmsAlias:
    stages:
      # list of stages for which the plugin should be enabled
      - production
```

Hope that helps!

**Comment by jgeurts** [comment]
Makes sense, could you please try v2.2.0?

**Comment by mishabruml** [comment]
that works perfectly, thank you! 🙇
